local g = vim.g
local o = vim.opt

g.mapleader = " "
o.wrap = false
o.smartindent = true
o.relativenumber = true
o.number = true
o.shiftwidth = 4
o.tabstop = 4
o.clipboard = "unnamedplus"
o.undofile = true
o.undolevels = 10000
o.foldcolumn = "1"
o.foldlevel = 99
o.foldlevelstart = 99
o.foldenable = true
o.fillchars = {
	eob = " ",
	fold = " ",
	foldopen = "",
	foldsep = " ",
	foldclose = "",
	wbr = " ",
	horiz = " ",
	horizup = " ",
	horizdown = " ",
	vert = " ",
	vertleft = " ",
	vertright = " ",
	verthoriz = " ",
}
o.sessionoptions = "buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"
o.laststatus = 3
o.updatetime = 200
o.showmode = false
o.smoothscroll = true
o.linebreak = true
